spring.application.name=estudantil
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://db.ysotamtlhrtqsbnfmonx.supabase.co:5432/postgres?user=postgres&password=password
spring.datasource.username=postgres
spring.datasource.password=password
api.security.token.secret=gM8MRlTO2Y9kB10JVscM83cWeukJGhXA
spring.jpa.properties.hibernate.type.preferred_enum_type=pgsql
logging.level.org.springframework.security=DEBUG
jwt.secret=40zL5Lvzr3etDufXcICINhqyPU90TYB0
supabase.url=https://ysotamtlhrtqsbnfmonx.supabase.co
supabase.service.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzb3RhbXRsaHJ0cXNibmZtb254Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDQ1MzI3NCwiZXhwIjoyMDc2MDI5Mjc0fQ.0iz51AqKtRBlU1Vb8CczcKKPZRLyf8utuXzCypYyqMs

# Configurações de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sgmepuc@gmail.com
spring.mail.password=jmfz hlam ztcg uswj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true